# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0bcb9ba2c2391a07b927cdedab4f01ac7d50cb055d6c88b1f31ba2c836d5cdc809f75f0ef5c4a119f447915670fac214bba3874783c57ca1d62a8412f276f550

test:
  secret_key_base: d402f54ab312fc67637436de71da3d14befc3bd7afe7632665b9ba2be3e15f7b04b323018eda4debd8d5f38c4b6306c4b88f5616a27e079c495a434f96a0bd9c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
